### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by denisalevi**
- [x] Installation instructions (first version with `pip` + CUDA requirements etc.) [WIP]
- [x] Finish example function to test install. 
- [x] Add support for running test suite via `brian2cuda.test()` (already documented)
- [x] Make failing test suite test that are documented as known issues not fail the test suite (expected fails)
- [x] Document our `gpu_tools`
- [ ] (optional, for later?) Document general performance consideration
- [ ] Document partitioning
- [x] Document known issues
- [ ] Update main README (remove or reduce install instructions and link to readthedocs page instead)
- [ ] (later) If we have a conda package, add install instructions (including optional `nvcc_linux64` to pick installation). Use tabs as in new Brian2 docs

### CODE REVIEW

**Comment by denisalevi** [comment]
I think I managed to get the largest part of the docs done. Few points are still missing, but could also be added later.

@mstimberg If you have time, would have a look through the docs if something important is missing?

Also there are two issues I didn't solve yet:
1. On the preference page, the preferences are sometimes bold and sometimes now. I didn't figure out why.
2. And I tried to change the name of the docs to `Brian2CUDA` instead of `brian2cuda`, but it doesn't show on the top left of the docs. Do you know where to change that?

**Comment by mstimberg** [comment]
> Also there are two issues I didn't solve yet:

The two issues should be solved with my commits, I'll have a closer look at the docs soon.

**Comment by mstimberg** [comment]
The docs look good to me :+1:, I only fixed a few broken links and typos that I spotted. The only thing that is missing is the "Known Issues" section, but a minimal version could maybe simply link to the issues here on github? To distinguish general optimization/refactoring issues from issues that a user might be interested in, we could have a "known issue" tag and simply link to the corresponding filter page, i.e. something like https://github.com/brian-team/brian2cuda/issues?q=is%3Aissue+is%3Aopen+label%3Abug but for the "known issue" tag.

**Comment by denisalevi** [comment]
Thanks for looking through it!
There is a "Known issue" page, which hasn't been filled yet, but has a link to the `bug` tags, just as you suggested (I copied it from the Brian docs ;)). Those are all issues that are actually bugs and that we are aware of, so I think that already is known issues (excluding optimizations etc.), or is there something you would remove from the known issues?

**Comment by mstimberg** [comment]
Ha, I didn't see that this links to the bugs, I thought it was a link to the general issue page :blush: 
Some of the "bugs" seem to be rather performance considerations (e.g. #142) and some are probably quite outdated (#63), but I wouldn't worry about it too much.

**Pull request merged**
