### PR TITLE
Update brian2cuda to use brian2 release 2.0

### PR DESCRIPTION
**Pull request by denisalevi**
This is the PR for #22 . 
Opening this to keep an overview of the changes that have or haven't been done. And to possibly help answering some questions that will follow below :)

### CODE REVIEW

**Comment by denisalevi** [comment]
Current state: feature tests are all passing, brian2 test suit for cuda_standalone specific: 109 tests, 49 errors, 7 failures (quite a few are of the same source).

@mstimberg Currently I'm looking at [this failing test](https://github.com/brian-team/brian2/blob/e83dbb14b3a533b3450c26b90a77c5c8463b7faf/brian2/tests/test_functions.py#L111-L136). It fails because a host function is called from inside a kernel. So in the function code it needs a `__device__` decorator (and if also used from host side additionally a `__host__` decorator). So it would need another `@implementation` decorator in the test function with a cuda implementation. Is there an intended way to adapt the testing functions for other devices? Otherwise I would probably just overwrite those test functions hat need adaption for cuda with my own ones? But this way it would be easy to oversee brian2 changes in those test functions.

**Comment by mstimberg** [comment]
Ok, there are several issues here. The first question is about the decision what implementation of a function should be used. Currently, our system is a bit messy and does allow too much: it checks for implementation for the `CodeObject` class and for the `CodeGenerator` class, but also for any implementation of a super class of either the `CodeObject` or the `CodeGenerator`. This is the problem in that test you linked to: `usersin` has an implementation for the `CPPCodeGenerator` class, and since your `CUDACodeGenerator` class inherits from that, the implementation will be considered as "good enough". I'll open an issue about this in Brian 2 itself, we need to handle this more carefully/flexibly.
The way `brian2genn` worked around this problem is by having its equivalent to `CUDACodeGenerator` *not* inherit from `CPPCodeGenerator`, but instead reimplement all the functions. This is a lot of copy&paste and certainly not the way it should be, but it could be a short-term solution.

About the tests in general: I would not overwrite individual tests, that will become messy over time. What we tried to do for `brian2genn` (and which is currently the case) is that each `standalone_compatible` test should either succeed or raise a `NotImplementedError`. Of course that means that the `test_user_defined_function` test from above will be counted as "not implemented" even though the CUDA device *does* support user-defined functions. In the long run, that test should probably be not marked as standalone-compatible, but have a separate test for runtime and standalone.

Now, for `brian2cuda` and `brian2genn` we'll of course want to have tests that are not shipped as part of `brian2`, but with the respective package. I don't think that you should write your own test runner function (even more so since in the future we will probably switch from `nose` to `py.test`), apart from a convenience script (like [this one](https://github.com/brian-team/brian2genn/blob/master/scripts/run_brian_tests.py)). I'd rather extend our current system so that it also deals with this use case. We would do this based on the `attr` annotations:

`@attr('codegen-independent')` : run once, independent of codegen target
no `@attr` annotation : run once for every runtime codegen target
`@attr('standalone-compatible')` : run once for every target (runtime + standalone)
`@attr('standalone-only', 'cpp_standalone')` : run only for `cpp_standalone`
`@attr('standalone-only', 'cuda_standalone')` : run only for `cuda_standalone`
etc.
The last two lines do not work yet, currently `standalone-only` is hardcoded to "only for cpp_standalone". Since `brian2cuda` (or `brian2genn`) tests are not shipped in the main Brian 2 package, Brian's test function needs one more argument, a folder name where to find the additional tests (or a list of folders maybe).

What do you think of this approach, would this work for you?

**Comment by denisalevi** [comment]
> The way brian2genn worked around this problem is by having its equivalent to CUDACodeGenerator not inherit from CPPCodeGenerator, but instead reimplement all the functions. This is a lot of copy&paste and certainly not the way it should be, but it could be a short-term solution.

Alright, this is done fast and can be reverted easily. I'll do that for now.

> About the tests in general: I would not overwrite individual tests, that will become messy over time. 

Yes, I would definitely prefer to avoid it.

> What we tried to do for brian2genn (and which is currently the case) is that each standalone_compatible test should either succeed or raise a NotImplementedError. Of course that means that the test_user_defined_function test from above will be counted as "not implemented" even though the CUDA device does support user-defined functions. In the long run, that test should probably be not marked as standalone-compatible, but have a separate test for runtime and standalone.

So instead of `@attr('standalone-compatible')` having `@attr('standalone-only', 'cpp_standalone')`? Then other devices could just use the cpp test and adapt it like this:
```python
from brian2.tests.test_functions import test_user_defined_functions

@attr('cuda_standalone')
test_user_defined_functions.usesin.imlementations.add_implementation('cuda', code='...')
```

> currently standalone-only is hardcoded to "only for cpp_standalone". Since brian2cuda (or brian2genn) tests are not shipped in the main Brian 2 package, Brian's test function needs one more argument, a folder name where to find the additional tests (or a list of folders maybe).
> What do you think of this approach, would this work for you?

This makes things much easier for me, so yeah, works for me!

**Comment by mstimberg** [comment]
Hmm, yes, I had in mind having one test function for device in that case. I guess we *could* make this more general, but I am not sure this is worth the complication.

**Comment by mstimberg** [comment]
Just to mention this here: with current Brian 2 master, `brian2.test()` takes an optional `extra_test_dirs` argument (a directory or a list of directories) where it will look for additional tests. The test attributes basically follow what I described above, see the updated docs (http://brian2.readthedocs.io/en/latest/developer/guidelines/testing.html) for an overview.

**Comment by denisalevi** [comment]
@mstimberg Thanks for the update.

**Comment by denisalevi** [comment]
Currently there are 8 ERRORS (compiler error), 10 FAILURES (tests fail) and 10 NOT_IMPLEMENTED (tests needing cuda implementations of some functions). These are of lower priority right no, so I have created issues for these (#46, #47, #48, #49, #50).
Merging this.

**Comment by mstimberg** [comment]
> I guess updating to be compatible with current master should do the job though I have not checked the diff of master vs 2.1.3

For now, master and the latest release (2.1.3.1) are exactly the same.

**Pull request merged**
